# Generated by Django 5.0.2 on 2024-02-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=200)),
                ('sentence_use', models.CharField(max_length=200)),
            ],
        ),
    ]
